
package Client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EmployeeAlreadyExists", targetNamespace = "http://Server/")
public class EmployeeAlreadyExists_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EmployeeAlreadyExists faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EmployeeAlreadyExists_Exception(String message, EmployeeAlreadyExists faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EmployeeAlreadyExists_Exception(String message, EmployeeAlreadyExists faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: Client.EmployeeAlreadyExists
     */
    public EmployeeAlreadyExists getFaultInfo() {
        return faultInfo;
    }

}
