
package Client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EmployeeNotFound", targetNamespace = "http://Server/")
public class EmployeeNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EmployeeNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EmployeeNotFound_Exception(String message, EmployeeNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EmployeeNotFound_Exception(String message, EmployeeNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: Client.EmployeeNotFound
     */
    public EmployeeNotFound getFaultInfo() {
        return faultInfo;
    }

}
